### ISSUE TITLE
This is a fabulous tool! 

### ISSUE THREAD

**Issue by lyoungblood14** [sachit27/greenR#1]
This is a fabulous tool! I'm curious about data completeness- have you thought about informing the user of how complete the underlying data is? OSM is not very complete when it comes to greenness last time I checked.

**Comment by sachit27** [comment]
Thank you for your insightful feedback! Ensuring data completeness is indeed a vital aspect of working with OSM, and I appreciate you highlighting this area. Currently, the package may not provide specific information about data completeness, and this is primarily a reflection of the limited availability of reference data. However, there's exciting progress being made, especially in providing ground truth for building data to enhance our understanding of OSM building information. While I'm currently unaware of any specific reference datasets for green spaces, your ideas and any resources you may have are more than welcome! If you share them, I will gladly explore possibilities to incorporate those insights into the package.
