### ISSUE TITLE
Detect Nominatim issues

### ISSUE THREAD

**Issue by loleg** [sachit27/greenR#2]
Really excellent initiative, thanks for the efforts here! I had a small problem using RStudio Cloud, since the server is at the moment banned from the Nominatim public endpoint. The error message was quite confusing at first, we should probably pick up a failed request. It would be great if we could add the ability to configure an alternative server and credentials.

**Comment by sachit27** [comment]
Thank you for your feedback! 
Based on the issue you reported with RStudio Cloud and the Nominatim public endpoint, I've made some adjustments to the get_osm_data function. Now, you can configure it with an alternative server URL and credentials if needed. Here's how you can use the updated function:
```
osm_data <- get_osm_data(bbox = "Fulham, London, United Kingdom",
                         server_url = "https://your-custom-server.com/search",
                         username = "your-username",
                         password = "your-password")
```
Can you test this updated function and let me know if it resolves the issues you were facing. I haven't configured an alternative server myself, but I looked at the documentation of Nominatim, and with the private url and the credentials, it should work.
