### ISSUE TITLE
Tags for OSM Download

### ISSUE THREAD

**Issue by redfrexx** [sachit27/greenR#3]
Hey great tool! :) One question: looking at the OSM download in [`get_osm_data.R`](https://github.com/sachit27/greenR/blob/99d084e8627107a89bafb3380ca350157e889814/R/get_osm_data.R#L68-L71), it seems like features are downloaded with the tag `landuse=park`. This tag doesn't exist though, I assume it should be `leisure=park`? I'm not an R expert, so maybe I've also misinterpreted the code here, but otherwise it would be worth having a look at it to get the intended features from OSM.

**Comment by sachit27** [comment]
Hi, thank you for your feedback and pointing it out. Actually, I had seen some instances where parks were tagged with both "landuse" and "leisure" but I checked the documentation again and the correct approach is to have leisure=park, like you mentioned.

I have updated the [get_osm_data.R](https://github.com/sachit27/greenR/blob/main/R/get_osm_data.R) function with the correct tags. Let me know if you have any more suggestions or feedback. :)
